@echo off
if ""=="%~1" SET WORKBENCH_DIR=%~dp0..
if not ""=="%~1" SET WORKBENCH_DIR=%~1

SET THINSTALL_BIN=%WORKBENCH_DIR%\Thinapp
SET WORKBENCH_PATH=%WORKBENCH_DIR%\Script
SET WORKBENCH_PATH=%WORKBENCH_PATH%;%THINSTALL_BIN%
SET WORKBENCH_PATH=%WORKBENCH_PATH%;%WORKBENCH_DIR%\AkelPad
SET WORKBENCH_PATH=%WORKBENCH_PATH%;%WORKBENCH_DIR%\tcmd750


SET PATH=%WORKBENCH_PATH%;%PATH%
SET WORKBENCH_PATH=

echo WORKBENCH : %WORKBENCH_DIR%
echo THINSTALL : %THINSTALL_BIN%